#! /bin/sh
set -e
#export GLOBUS_LOCATION=/usr/local/globus-4.0.5
#export JAVA_HOME=/usr/local/j2sdk1.4.2_01
#export ANT_HOME=/usr/local/apache-ant-1.7.0
#export GLOBUS_OPTIONS="-Xms256M -Xmx512M"

#. $GLOBUS_LOCATION/etc/globus-user-env.sh


#cd $GLOBUS_LOCATION

case "$1" in
    1)
    	export CLASSPATH=$CLASSPATH:/home/kim/service/workspace/ServiceCube/src/build/stubs/classes
    	./globus-build-service.sh -d org/drs/service/ -s schema/examples/Cube/DRS.wsdl
	cp org_drs_service.gar /dados/
	echo "cp org_drs_service.gar to /dados/"
        ;;
    2)
    	echo "Compiling..."
        javac -classpath ./build/stubs/classes/:$CLASSPATH org/cubeindex/client/ClientIndex.java
	echo "Compiled" >&2
        ;;
    3)
    	echo "Executing..."
    	java -classpath ./build/stubs/classes/:$CLASSPATH org.cubeindex.client.ClientIndex http://eingrid001.unigranrio.br:8443/wsrf/services/cubeIndex
    	;;
    4)
    	echo "Compiling..."
        javac -classpath ./build/stubs/classes/:$CLASSPATH org/cubeindex/client/ClientIndex.java
	echo "Executing..."
	java -classpath ./build/stubs/classes/:$CLASSPATH org.cubeindex.client.ClientIndex http://eingrid002.unigranrio.br:8443/wsrf/services/cubeIndex
    	;;
    5)
    	cp -r -f build/stubs/classes/* ../../ServiceCube/src/build/stubs/classes/
	echo "cp -r -f 'stubs/' to ServiceCube/stubs'" >&2
	;;
    toweb)
    		#prj Antigo
    	#cp -r build/stubs/classes/org/ ../../WebAppCube/cube/web/WEB-INF/classes/
    	#echo "Copied ./build/stubs/classes/ to WebAppCube/.../classes" >&2

		#prj Atual
	#cp -r build/stubs/classes/org/ ../../prjClienteWebDRS/build/stubs/
	#echo "Copied ./build/stubs/classes/ to prjClienteWebDRS/build/stubs"

		#Diretamente na Lib do TomCat
	cp build/lib/org_drs_service_stubs.jar $CATALINA_HOME/lib
        echo "cp build/lib/stubsDRS.jar to 'CATALINA_HOME'/lib"
    ;;
    *)
        echo "Usage: s {1|2|3|4}" >&2
        # exit 1
       ;;
esac
#exit 0

